### ISSUE TITLE
Any updates on this?

### ISSUE THREAD

**Issue by viksit** [cvangysel/cuNVSM#1]
Are there any ETAs on the code being released? Thanks.

**Comment by forwidur** [comment]
Really looking forward to this too. :-)

**Comment by cvangysel** [comment]
I'm working on it. :-)

This is probably not what you're after, but I recently released part of the cuNVSM code as a separate project: https://github.com/cvangysel/device_matrix.

**Comment by forwidur** [comment]
Thanks for the update, Christophe! I was under the assumption that the code was ready at the time paper was released, hence wondering about this repo.

The `device_matrix` looks interesting, but indeed, I'd really love to see the entire cuNVSM released.

Thank you for your work! :-)

**Comment by cvangysel** [comment]
Just a quick heads up that this will be released soon (i.e., by the end of this week). I'm just running a few more tests on different systems to hash out any last build/compilation problems.

**Comment by forwidur** [comment]
Thank you, @cvangysel! I'm really looking forward giving it a spin! :-D

**Comment by cvangysel** [comment]
Sorry again for the delay. I encountered some last minute issues that occurred when using different versions of CMake.

Closing this issue as it's all there now. :-)
