### ISSUE TITLE
Train/predict consistent?

### ISSUE THREAD

**Issue by aaholmes** [cvangysel/cuNVSM#2]
It looks like querying uses cosine similarity between transformed phrase and doc embeddings, but the loss function depends on the dot product between them instead (so e.g. the L2 norms of the doc embeddings are used in training but not in predicting). Is that right?

**Comment by cvangysel** [comment]
That's correct. The loss function is an unsupervised approximation to the text matching problem.

Documents that just contain a single word a bunch of times (i.e., easy to learn representations) can cause the magnitude of their representations to blow up during training, as the gradient always points in the same direction. This also happens with short documents as we just sample the same n-gram over and over again.

Using cosine similarity during ranking avoids this problem.
